version: '3.0'
services:
  evrent1:
    container_name: EV_Rent1
    build: "isosim:latest"
    ports:
      - "9090:9090"
    environment:
      ENV: DEV
    volumes:
      - .:/usr/src
  #    links:
  #      - logspout
  evrent2:
    container_name: EV_Rent2
    build: "isosim:latest"
    ports:
      - "9091:9090"
    environment:
      ENV: DEV
    volumes:
      - .:/usr/src
  #    links:
  #      - logspout

  nginx:
    container_name: nginx
    image: "nginx:test"
    ports:
      - "80:80"